flask-app:
  build: .
  container_name: flask-app
  ports:
    - "5000:5000"
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  environment:
    - FLASK_APP=app.py
    - FLASK_ENV=development
    - REDIS_URL=redis://redis:6379/0
    - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/mydatabase
  depends_on:
    - db
    - redis
  volumes:
    - .:/app
  networks:
    - app-network
