version: '3.8'

services:
  # Flask application
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - app-network

  # PostgreSQL service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - .:/app
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:6
    container_name: redis
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
