version: '3.8'

services:
  # Flask application
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - app-network

  # PostgreSQL service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase

    networks:
      - app-network

  # Redis service
  redis:
    image: redis:6
    container_name: redis
    networks:
      - app-network


  nginx:
      image: nginx:latest
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
      - flask-app
      ports:
        - "80:80"
      networks:
        - app-network



volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
