"""empty message

Revision ID: 174fb45a580a
Revises: b2446d089768
Create Date: 2025-01-27 16:11:51.337376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174fb45a580a'
down_revision = 'b2446d089768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
