"""add lead_status

Revision ID: b2446d089768
Revises: 318ddc28e22a
Create Date: 2025-01-21 11:04:05.341099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2446d089768'
down_revision = '318ddc28e22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('audio_text', sa.String(), nullable=True),
    sa.Column('analysed_text', sa.String(), nullable=True),
    sa.Column('is_analysed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_status', sa.String(), nullable=True))
        batch_op.drop_column('path')

    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_permissions', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_column('is_permissions')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('lead_status')

    op.drop_table('analyses')
    # ### end Alembic commands ###
